<template>
  <VerticalLayout>
    <b-card :title="isAdmin ? 'Create product (Admin)' : 'Create product'" class="mb-0">
      <p class="text-muted">
        Step 1: Product information. Step 2: Specification (add as many as you like). Step 3: Images and cover.
        You can save as draft at any time. New products are under review and visible to buyers after admin approval.
      </p>
      <form-wizard
        ref="wizardRef"
        color="#5C308F"
        back-button-text="Back"
        next-button-text="Next"
        finish-button-text="Create product"
        @on-complete="onComplete"
      >
        <tab-content title="Product information">
          <div class="d-flex justify-content-end mb-2">
            <b-button variant="outline-secondary" size="sm" @click="saveDraft">Save as draft</b-button>
          </div>
          <b-row>
            <b-col md="6">
              <b-form-group class="mb-3">
                <template #label>
                  <span class="d-inline-flex align-items-center">Title
                    <b-button variant="link" class="p-0 ms-1 text-secondary align-baseline" size="sm" id="help-create-title" aria-label="What is needed"><small>ⓘ</small></b-button>
                    <b-tooltip target="help-create-title" triggers="click" placement="top">Required. The product name as shown to buyers (max 160 characters).</b-tooltip>
                  </span>
                </template>
                <b-form-input id="title" v-model="form.title" placeholder="Product title" maxlength="160" required />
              </b-form-group>
            </b-col>
            <b-col cols="12">
              <b-form-group class="mb-3">
                <template #label>
                  <span class="d-inline-flex align-items-center">Description (min 200 characters for publish)
                    <b-button variant="link" class="p-0 ms-1 text-secondary align-baseline" size="sm" id="help-create-desc" aria-label="What is needed"><small>ⓘ</small></b-button>
                    <b-tooltip target="help-create-desc" triggers="click" placement="top">At least 200 characters are required to publish. You can save as draft with less.</b-tooltip>
                  </span>
                </template>
                <b-form-textarea id="description" v-model="form.description" rows="4" placeholder="Full product description..." />
                <small class="text-muted">{{ (form.description || '').length }} / 200</small>
              </b-form-group>
            </b-col>
            <b-col cols="12">
              <CatalogCategoryPicker v-model="form.categories" :use-admin-categories="isAdmin" />
            </b-col>
            <b-col md="6">
              <b-form-group label="Brand" class="mb-3">
                <b-form-select v-model="form.brand" :options="brandOptions" value-field="slug" text-field="name">
                  <template #first>
                    <b-form-select-option :value="''">— Select —</b-form-select-option>
                  </template>
                </b-form-select>
              </b-form-group>
            </b-col>
            <b-col md="4">
              <b-form-group label="Base price" class="mb-3">
                <b-form-input v-model.number="form.base_price" type="number" step="0.01" min="0" placeholder="0.00" />
              </b-form-group>
            </b-col>
            <b-col md="4">
              <b-form-group label="Discount price (optional)" class="mb-3">
                <b-form-input v-model.number="form.discount_price" type="number" step="0.01" min="0" placeholder="" />
              </b-form-group>
            </b-col>
            <b-col md="4">
              <b-form-group label="Weight (kg, optional)" class="mb-3">
                <b-form-input v-model.number="form.weight_kg" type="number" step="0.01" min="0" placeholder="" />
              </b-form-group>
            </b-col>
            <b-col cols="12">
              <h6 class="mb-2 d-inline-flex align-items-center">
                SKUs (at least one)
                <b-button variant="link" class="p-0 ms-1 text-secondary align-baseline" size="sm" id="help-create-skus" aria-label="What is needed"><small>ⓘ</small></b-button>
                <b-tooltip target="help-create-skus" triggers="click" placement="top">Add at least one SKU. Stock is required. Use variation template (Color, Weight, Size) or a custom Variant (e.g. size:M). Price override is optional; otherwise base price is used. SKU code is auto-generated by the system.</b-tooltip>
              </h6>
              <b-form-checkbox v-model="form.useVariationTemplate" class="mb-2">
                Use variation template (Color, Weight, Size)
              </b-form-checkbox>
              <div v-for="(sku, idx) in form.skus" :key="idx" class="border rounded p-3 mb-3">
                <b-row>
                  <template v-if="form.useVariationTemplate">
                    <b-col md="2">
                      <b-form-group label="Color" class="mb-2">
                        <b-form-input v-model="sku.color" placeholder="e.g. Red" />
                      </b-form-group>
                    </b-col>
                    <b-col md="2">
                      <b-form-group label="Weight" class="mb-2">
                        <b-form-input v-model="sku.weight" placeholder="e.g. 50g, 100g" />
                      </b-form-group>
                    </b-col>
                    <b-col md="2">
                      <b-form-group label="Size" class="mb-2">
                        <b-form-input v-model="sku.size" placeholder="e.g. S, M, L" />
                      </b-form-group>
                    </b-col>
                  </template>
                  <template v-else>
                    <b-col md="2">
                      <b-form-group label="Variant" class="mb-2">
                        <b-form-input v-model="sku.variant_text" placeholder="size:M" />
                      </b-form-group>
                    </b-col>
                  </template>
                  <b-col md="2">
                    <b-form-group label="Stock" class="mb-2">
                      <b-form-input v-model.number="sku.stock_quantity" type="number" min="0" />
                    </b-form-group>
                  </b-col>
                  <b-col md="2">
                    <b-form-group label="Price override" class="mb-2">
                      <b-form-input v-model.number="sku.price_override" type="number" step="0.01" min="0" placeholder="" />
                    </b-form-group>
                  </b-col>
                  <b-col md="2" class="d-flex align-items-end">
                    <b-button variant="outline-danger" size="sm" @click="removeSku(idx)">Remove</b-button>
                  </b-col>
                </b-row>
              </div>
              <b-button variant="outline-primary" @click="addSku">+ Add SKU</b-button>
            </b-col>
          </b-row>
        </tab-content>
        <tab-content title="Specification">
          <div class="d-flex justify-content-end mb-2">
            <b-button variant="outline-secondary" size="sm" @click="saveDraft">Save as draft</b-button>
          </div>
          <p class="text-muted mb-3 d-inline-flex align-items-center">
            Add specification entries. Choose input type, label, and value. You can add as many as you need.
            <b-button variant="link" class="p-0 ms-1 text-secondary align-baseline" size="sm" id="help-create-spec" aria-label="What is needed"><small>ⓘ</small></b-button>
            <b-tooltip target="help-create-spec" triggers="click" placement="top">Optional. Add key-value specs (e.g. Material: Cotton). Use input type Text, Number, or Long text. Label is the spec name; value is the spec value.</b-tooltip>
          </p>
          <div v-for="(spec, idx) in form.specifications" :key="idx" class="border rounded p-3 mb-3">
            <b-row>
              <b-col md="3">
                <b-form-group label="Input type" class="mb-2">
                  <b-form-select v-model="spec.input_type" :options="specInputTypeOptions" />
                </b-form-group>
              </b-col>
              <b-col md="3">
                <b-form-group label="Label" class="mb-2">
                  <b-form-input v-model="spec.label" placeholder="e.g. Color" />
                </b-form-group>
              </b-col>
              <b-col md="4">
                <b-form-group v-if="spec.input_type === 'textarea'" label="Value" class="mb-2">
                  <b-form-textarea v-model="spec.value" rows="2" placeholder="Value" />
                </b-form-group>
                <b-form-group v-else label="Value" class="mb-2">
                  <b-form-input v-model="spec.value" :type="spec.input_type === 'number' ? 'number' : 'text'" step="any" placeholder="Value" />
                </b-form-group>
              </b-col>
              <b-col md="2" class="d-flex align-items-end">
                <b-button variant="outline-danger" size="sm" @click="removeSpec(idx)">Remove</b-button>
              </b-col>
            </b-row>
          </div>
          <b-button variant="outline-primary" @click="addSpec">+ Add specification</b-button>
        </tab-content>
        <tab-content title="Images &amp; cover">
          <div class="d-flex justify-content-end mb-2">
            <b-button variant="outline-secondary" size="sm" @click="saveDraft">Save as draft</b-button>
          </div>
          <p class="text-muted mb-3 d-inline-flex align-items-center">
            Upload or enter image URLs. First image or selected cover is used as cover.
            <b-button variant="link" class="p-0 ms-1 text-secondary align-baseline" size="sm" id="help-create-images" aria-label="What is needed"><small>ⓘ</small></b-button>
            <b-tooltip target="help-create-images" triggers="click" placement="top">Optional. Add a cover image (file or URL) and/or gallery images. First image becomes the cover. You can add more URLs in the text area, one per line.</b-tooltip>
          </p>
          <b-form-group label="Cover image" class="mb-3">
            <div v-if="coverPreviewUrl" class="mb-2">
              <img :src="coverPreviewUrl" alt="Cover" class="product-wizard-cover-preview" />
            </div>
            <b-form-input v-model="form.cover_image" placeholder="Cover image URL (optional)" class="mb-2" />
            <input type="file" accept="image/*" class="form-control mb-2" @change="onCoverFileChange" />
          </b-form-group>
          <b-form-group label="Gallery images (multi upload)">
            <input type="file" accept="image/*" multiple class="form-control mb-2" @change="onGalleryFilesChange" />
            <div v-if="form.gallery_files.length" class="d-flex flex-wrap gap-2 mt-2">
              <div v-for="(file, i) in form.gallery_files" :key="i" class="gallery-thumb-wrap">
                <img :src="galleryPreview(file)" alt="" class="gallery-thumb" />
                <b-button size="sm" variant="outline-danger" class="mt-1" @click="removeGalleryFile(i)">Remove</b-button>
              </div>
            </div>
          </b-form-group>
          <b-form-group label="Additional image URLs (one per line)">
            <b-form-textarea v-model="form.additional_images_text" rows="2" placeholder="https://..." />
          </b-form-group>
          <p v-if="submitting" class="text-muted mt-2 mb-0">Saving product…</p>
          <p v-else-if="submitError" class="text-danger mt-2 mb-0">{{ submitError }}</p>
        </tab-content>
      </form-wizard>
      <ImageUploadProgressBar
        :visible="imageUploadActive"
        subtitle="Uploading images…"
        :percent="imageUploadPercent"
        :pulse-striped="imageUploadPulse"
      />
    </b-card>
  </VerticalLayout>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, onBeforeUnmount, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import VerticalLayout from '@/layouts/VerticalLayout.vue'
import CatalogCategoryPicker from '@/components/kkoo/CatalogCategoryPicker.vue'
import ImageUploadProgressBar from '@/components/ImageUploadProgressBar.vue'
import { FormWizard, TabContent } from 'vue3-form-wizard'
import 'vue3-form-wizard/dist/style.css'
import { catalogPublicApi, catalogSellerApi, catalogAdminApi } from '@/api'
import { useMultipartUploadProgress } from '@/composables/useMultipartUploadProgress'
import { formatApiError } from '@/utils/formatApiError'
import { toastError, toastSuccess } from '@/utils/toast'

const router = useRouter()
const route = useRoute()
const isAdmin = computed(() => route.path.startsWith('/admin/catalog'))
const brandOptions = ref<{ slug: string; name: string }[]>([])
const submitError = ref('')
const submitting = ref(false)
const wizardRef = ref<InstanceType<typeof FormWizard> | null>(null)
const galleryUrlByFile = new WeakMap<File, string>()
let coverObjectUrl: string | null = null
const {
  uploadActive: imageUploadActive,
  uploadPercent: imageUploadPercent,
  uploadPulse: imageUploadPulse,
  beginUpload: beginImageUpload,
  onUploadProgress: onImageUploadProgress,
  endUpload: endImageUpload,
} = useMultipartUploadProgress()

const specInputTypeOptions = [
  { value: 'text', text: 'Text' },
  { value: 'number', text: 'Number' },
  { value: 'textarea', text: 'Long text' },
]

const form = reactive({
  title: '',
  description: '',
  categories: [] as string[],
  brand: '',
  base_price: 0 as number | string,
  discount_price: null as number | null | string,
  weight_kg: null as number | null | string,
  useVariationTemplate: false,
  skus: [] as { stock_quantity: number; price_override?: number | null; variant_text?: string; color?: string; weight?: string; size?: string }[],
  specifications: [] as { input_type: string; label: string; value: string }[],
  cover_image: '',
  cover_file: null as File | null,
  gallery_files: [] as File[],
  additional_images_text: '',
})

const coverPreviewUrl = ref('')

watch(
  () => [form.cover_file, form.cover_image] as const,
  () => {
    if (coverObjectUrl) {
      URL.revokeObjectURL(coverObjectUrl)
      coverObjectUrl = null
    }
    if (form.cover_file) {
      coverObjectUrl = URL.createObjectURL(form.cover_file)
      coverPreviewUrl.value = coverObjectUrl
    } else {
      coverPreviewUrl.value = form.cover_image?.trim() || ''
    }
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  if (coverObjectUrl) URL.revokeObjectURL(coverObjectUrl)
  for (const file of form.gallery_files) {
    const url = galleryUrlByFile.get(file)
    if (url) URL.revokeObjectURL(url)
  }
})

function addSku() {
  form.skus.push({
    stock_quantity: 0,
    price_override: null,
    variant_text: '',
    color: '',
    weight: '',
    size: '',
  })
}
function removeSku(idx: number) {
  form.skus.splice(idx, 1)
}
function addSpec() {
  form.specifications.push({ input_type: 'text', label: '', value: '' })
}
function removeSpec(idx: number) {
  form.specifications.splice(idx, 1)
}
function onCoverFileChange(ev: Event) {
  const input = ev.target as HTMLInputElement
  form.cover_file = input.files?.[0] ?? null
  if (form.cover_file) form.cover_image = ''
}
function onGalleryFilesChange(ev: Event) {
  const input = ev.target as HTMLInputElement
  const files = input.files ? Array.from(input.files) : []
  form.gallery_files.push(...files)
  input.value = ''
}
function galleryPreview(file: File): string {
  let url = galleryUrlByFile.get(file)
  if (!url) {
    url = URL.createObjectURL(file)
    galleryUrlByFile.set(file, url)
  }
  return url
}
function removeGalleryFile(idx: number) {
  const file = form.gallery_files[idx]
  const url = file ? galleryUrlByFile.get(file) : undefined
  if (url) {
    URL.revokeObjectURL(url)
    galleryUrlByFile.delete(file)
  }
  form.gallery_files.splice(idx, 1)
}

function buildSpecificationObject(): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const s of form.specifications) {
    if (s.label?.trim()) out[s.label.trim()] = s.value ?? ''
  }
  return out
}

const VARIANT_DIMENSIONS = ['color', 'weight', 'size'] as const

function buildPayload(asDraft: boolean): Record<string, unknown> {
  const variantAttrs = form.skus.map((s) => {
    if (form.useVariationTemplate) {
      const attrs: Record<string, string> = {}
      if (s.color?.trim()) attrs.color = s.color.trim()
      if (s.weight?.trim()) attrs.weight = s.weight.trim()
      if (s.size?.trim()) attrs.size = s.size.trim()
      return attrs
    }
    const attrs: Record<string, string> = {}
    if (s.variant_text) {
      const [k, v] = s.variant_text.split(':').map((x) => x.trim())
      if (k) attrs[k] = v || ''
    }
    return attrs
  })
  const specs = { ...buildSpecificationObject() }
  if (form.useVariationTemplate) (specs as Record<string, unknown>).variant_dimensions = [...VARIANT_DIMENSIONS]
  const payload: Record<string, unknown> = {
    title: form.title,
    description: form.description || '',
    category_slugs: form.categories?.length ? [...form.categories] : undefined,
    brand: form.brand || undefined,
    base_price: Number(form.base_price) || 0,
    skus: form.skus.map((s, i) => ({
      stock_quantity: Number(s.stock_quantity) || 0,
      price_override: s.price_override != null && String(s.price_override) !== '' ? Number(s.price_override) : null,
      variant_attributes: variantAttrs[i] || {},
    })),
    specification: { specs },
  }
  payload.status = asDraft ? 'draft' : 'published'
  if (form.discount_price != null && String(form.discount_price) !== '') {
    const d = Number(form.discount_price)
    if (Number.isFinite(d)) payload.discount_price = d
  }
  if (form.weight_kg != null && String(form.weight_kg) !== '') {
    const w = Number(form.weight_kg)
    if (Number.isFinite(w)) payload.weight_kg = w
  }
  if (form.cover_image?.trim() && !form.cover_file) payload.cover_image = form.cover_image.trim()
  return payload
}

function validateBeforeSubmit(asDraft: boolean): string | null {
  if (!form.title.trim()) return 'Product title is required.'
  if (form.title.trim().length > 160) return 'Product title must be at most 160 characters.'
  if (!asDraft && (form.description || '').length < 200) {
    return 'Description must be at least 200 characters to publish.'
  }
  if (!asDraft && (!form.skus.length || form.skus.some((s) => Number(s.stock_quantity ?? 0) < 0))) {
    return 'Add at least one SKU with stock quantity ≥ 0.'
  }
  const price = Number(form.base_price)
  if (!asDraft && (!Number.isFinite(price) || price <= 0)) {
    return 'Base price must be greater than 0 to publish.'
  }
  return null
}

async function submitProduct(asDraft: boolean) {
  if (submitting.value) return
  submitError.value = ''
  const validationError = validateBeforeSubmit(asDraft)
  if (validationError) {
    submitError.value = validationError
    toastError(validationError)
    return
  }
  const payload = buildPayload(asDraft)
  submitting.value = true
  try {
    const createRes = isAdmin.value
      ? await catalogAdminApi.createProduct(payload)
      : await catalogSellerApi.createProduct(payload)
    const data = (createRes.data ?? {}) as Record<string, unknown>
    const createdSlug = data.slug ? String(data.slug) : null
    if (!createdSlug) {
      throw new Error('Product was created but no slug was returned. Refresh the product list.')
    }
    const hasImages = form.cover_file || form.gallery_files.length
    if (hasImages) {
      const fd = new FormData()
      fd.append('title', form.title.trim())
      fd.append('description', form.description || '')
      fd.append('base_price', String(payload.base_price))
      fd.append('status', asDraft ? 'draft' : 'published')
      if (payload.specification) fd.append('specification', JSON.stringify(payload.specification))
      if (form.categories?.length) {
        fd.append('category_slugs', JSON.stringify(form.categories))
      }
      if (form.brand) fd.append('brand', form.brand)
      if (form.cover_file) fd.append('cover_image', form.cover_file)
      else if (form.gallery_files.length) fd.append('cover_image', form.gallery_files[0])
      form.gallery_files.forEach((file, i) => {
        if (form.cover_file) fd.append('images', file)
        else if (i > 0) fd.append('images', file)
      })
      beginImageUpload()
      try {
        if (isAdmin.value) {
          await catalogAdminApi.updateProductWithCover(createdSlug, fd, { onUploadProgress: onImageUploadProgress })
        } else {
          await catalogSellerApi.updateProductWithCover(createdSlug, fd, { onUploadProgress: onImageUploadProgress })
        }
      } catch (imgErr: unknown) {
        toastError(formatApiError(imgErr, 'Product saved, but image upload failed. Edit the product to add images.'))
      } finally {
        endImageUpload()
      }
    }
    toastSuccess(asDraft ? 'Draft saved' : 'Product created')
    await router.push(isAdmin.value ? { name: 'admin.catalog.products' } : { name: 'seller.products' })
  } catch (e: unknown) {
    submitError.value = formatApiError(e, 'Failed to save product')
    toastError(submitError.value)
  } finally {
    submitting.value = false
  }
}

async function saveDraft() {
  await submitProduct(true)
}

async function onComplete() {
  await submitProduct(false)
}

onMounted(async () => {
  const titleQ = typeof route.query.title === 'string' ? route.query.title.trim() : ''
  const descQ = typeof route.query.description === 'string' ? route.query.description.trim() : ''
  if (titleQ) form.title = titleQ.slice(0, 160)
  if (descQ) form.description = descQ

  try {
    const { data: brandData } = isAdmin.value
      ? await catalogAdminApi.listBrands()
      : await catalogPublicApi.listBrands()
    const brands = brandData as { results?: { slug: string; name: string }[] } | { slug: string; name: string }[]
    brandOptions.value = (Array.isArray(brands) ? brands : (brands?.results ?? [])).map((b) => ({
      slug: b.slug,
      name: b.name,
    }))
  } catch {
    brandOptions.value = []
  }
  if (form.skus.length === 0) addSku()
  if (form.specifications.length === 0) addSpec()
})
</script>

<style scoped>
.product-wizard-cover-preview {
  max-width: 200px;
  max-height: 140px;
  object-fit: contain;
  border-radius: 4px;
  border: 1px solid var(--bs-border-color, #dee2e6);
}
.gallery-thumb-wrap {
  width: 80px;
  text-align: center;
}
.gallery-thumb {
  width: 80px;
  height: 80px;
  object-fit: contain;
  border-radius: 4px;
  border: 1px solid var(--bs-border-color, #dee2e6);
}
</style>
