import type { AxiosRequestConfig } from 'axios'
import client from './client'

export type MissingProductReportStatus = 'pending' | 'reviewed' | 'added' | 'dismissed'

export type MissingProductReportMediaRow = {
  id?: number
  file_url?: string
  file_name?: string
  content_type?: string
  size_bytes?: number
}

export type MissingProductReportRow = {
  id?: number
  user_id?: number
  product_name?: string
  description?: string
  seller_id?: number | null
  category_id?: number | null
  status?: MissingProductReportStatus
  notify_admin?: boolean
  notify_seller?: boolean
  created_at?: string
  updated_at?: string
  media?: MissingProductReportMediaRow[]
}

/** Public catalog. API.md: categories, brands, products (with filters), recommended, by-id, by slug. */
export const catalogPublicApi = {
  listCategories() {
    return client.get<{ results: unknown[] }>('/catalog/categories/')
  },
  listBrands() {
    return client.get<{ results: unknown[] }>('/catalog/brands/')
  },
  /** API.md: category, category_slug, brand, seller_id, in_stock, min/max_price, tags, wholesale_only, ordering, page, page_size */
  listProducts(params?: {
    search?: string
    category?: string
    category_slug?: string
    brand?: string
    seller_id?: number
    in_stock?: boolean
    min_price?: number
    max_price?: number
    tags?: string
    wholesale_only?: boolean
    ordering?: 'price_asc' | 'price_desc' | 'newest' | 'oldest' | 'rating' | 'popular'
    min_rating?: number
    max_rating?: number
    page?: number
    page_size?: number
  }) {
    return client.get<{ results: unknown[]; count?: number; total?: number; page?: number }>('/catalog/products/', { params })
  },
  getRecommended(params?: {
    product_id?: number
    slug?: string
    strategy?: 'for_you' | 'trending' | 'recent'
    limit?: number
  }) {
    return client.get<{ results: unknown[]; source?: string }>('/catalog/products/recommended/', { params })
  },
  getProductById(id: number) {
    return client.get(`/catalog/products/by-id/${id}/`)
  },
  getProductBySlug(slug: string) {
    return client.get(`/catalog/products/${slug}/`)
  },
}

/** Search. API.md: autocomplete (q, limit), popular, history (auth), missing-keywords (seller/admin). */
export const catalogSearchApi = {
  autocomplete(params: { q: string; limit?: number }) {
    return client.get<{ products?: unknown[]; categories?: unknown[]; brands?: unknown[] }>('/catalog/search/autocomplete/', { params })
  },
  popular() {
    return client.get<{ popular_searches?: string[] }>('/catalog/search/popular/')
  },
  getHistory() {
    return client.get<{ search_history?: string[] }>('/catalog/search/history/')
  },
  saveHistory(query: string) {
    return client.post<{ message?: string }>('/catalog/search/history/', { query })
  },
  clearHistory() {
    return client.delete<{ message?: string }>('/catalog/search/history/')
  },
  missingKeywords(params?: { limit?: number; min_count?: number; since?: string }) {
    return client.get<{ missing_keywords?: { keyword: string; times_searched?: number; last_searched?: string }[]; count?: number }>('/catalog/search/missing-keywords/', { params })
  },
}

/** Admin categories. API.md: approval_status, is_active. */
export const catalogAdminCategoriesApi = {
  list(params?: { page?: number; search?: string; approval_status?: string; is_active?: boolean }) {
    return client.get('/catalog/admin/categories/', { params })
  },
  /** Create category or subcategory. Slug is backend-generated if omitted. parent = parent's slug or omit/null for top-level. */
  create(data: { name: string; slug?: string; parent?: string | null; description?: string; icon?: string }) {
    return client.post('/catalog/admin/categories/', data)
  },
  /** Create category with icon file (multipart). FormData: name, parent?, description?, icon (file). Slug generated by backend. */
  createWithImage(formData: FormData, config?: AxiosRequestConfig) {
    return client.post('/catalog/admin/categories/', formData, config)
  },
  get(slug: string) {
    return client.get(`/catalog/admin/categories/${slug}/`)
  },
  /** Update category; set parent to slug to move under another, or null for top-level. */
  update(slug: string, data: Record<string, unknown>) {
    return client.patch(`/catalog/admin/categories/${slug}/`, data)
  },
  /** Update category with icon file (multipart). FormData: name?, slug?, parent?, description?, icon (file). */
  updateWithImage(slug: string, formData: FormData, config?: AxiosRequestConfig) {
    return client.patch(`/catalog/admin/categories/${slug}/`, formData, config)
  },
  delete(slug: string) {
    return client.delete(`/catalog/admin/categories/${slug}/`)
  },
}

/** Per WEB_ADMIN_SELLER_API_GUIDE: catalog admin endpoints and payloads */
export const catalogAdminApi = {
  listBrands(params?: { page?: number; search?: string }) {
    return client.get('/catalog/admin/brands/', { params })
  },
  createBrand(data: { name: string; slug?: string; country_of_origin?: string; logo?: string }) {
    return client.post('/catalog/admin/brands/', data)
  },
  /** Create brand with logo file (multipart). Slug generated by backend. */
  createBrandWithLogo(formData: FormData, config?: AxiosRequestConfig) {
    return client.post('/catalog/admin/brands/', formData, config)
  },
  getBrand(slug: string) {
    return client.get(`/catalog/admin/brands/${slug}/`)
  },
  updateBrand(slug: string, data: Record<string, unknown>) {
    return client.patch(`/catalog/admin/brands/${slug}/`, data)
  },
  /** Update brand with logo file (multipart). Fiber: PATCH /catalog/admin/brands/:slug/ */
  updateBrandWithLogo(slug: string, formData: FormData, config?: AxiosRequestConfig) {
    return client.patch(`/catalog/admin/brands/${slug}/`, formData, config)
  },
  /** Soft-deactivate brand (no DELETE route on Fiber). */
  deactivateBrand(slug: string) {
    return client.patch(`/catalog/admin/brands/${slug}/`, { is_active: false })
  },
  /** Toggle verified flag via PATCH is_verified. */
  verifyBrand(slug: string, action: 'verify' | 'unverify' = 'verify') {
    return client.patch(`/catalog/admin/brands/${slug}/`, { is_verified: action === 'verify' })
  },
  /** API.md: search, verification_status, status (draft|published), is_active, page, page_size */
  listProducts(params?: {
    page?: number
    page_size?: number
    search?: string
    verification_status?: string
    status?: string
    is_active?: boolean
    seller?: string
    category_slug?: string
  }) {
    return client.get<{
      results: unknown[]
      total?: number
      count?: number
      page?: number
      page_size?: number
    }>('/catalog/admin/products/', { params })
  },
  /** Admin product detail by slug (same slug pattern as verify/deactivate). */
  getProductBySlug(slug: string) {
    return client.get(`/catalog/admin/products/${slug}/`)
  },
  /** Create product (admin). Uses shared catalog create endpoint (supports seller_id, category_slugs, brand slug). */
  createProduct(data: Record<string, unknown>) {
    return client.post('/catalog/products/create/', data)
  },
  /** Update product (admin). By slug. */
  updateProduct(slug: string, data: Record<string, unknown>) {
    return client.put(`/catalog/admin/products/${slug}/`, data)
  },
  /** Update product with cover image (admin, multipart). */
  updateProductWithCover(slug: string, formData: FormData, config?: AxiosRequestConfig) {
    return client.put(`/catalog/admin/products/${slug}/`, formData, config)
  },
  /** Body required: action "approve" | "reject". Per guide: by slug. */
  verifyProduct(slug: string, action: 'approve' | 'reject' = 'approve') {
    return client.post(`/catalog/admin/products/${slug}/verify/`, { action })
  },
  /** Deactivate via bulk action (Fiber has no per-slug deactivate route). */
  deactivateProduct(slug: string) {
    return client.post<{ updated?: number; action?: string }>('/catalog/admin/products/bulk/', {
      action: 'deactivate',
      slugs: [slug],
    })
  },
  /** API.md: product_id, is_verified (true|false), page, page_size */
  listMedia(params?: { product_id?: number; is_verified?: boolean; page?: number; page_size?: number }) {
    return client.get('/catalog/admin/media/', { params })
  },
  /** API.md: action "approve" | "reject"; reason or rejection_reason required when reject. */
  verifyMedia(id: number, payload: { action: 'approve' | 'reject'; reason?: string; rejection_reason?: string }) {
    return client.post(`/catalog/admin/media/${id}/verify/`, payload)
  },
  /** API.md: POST /catalog/admin/products/bulk/ — product_ids ([]uint) or slugs ([]string), action: approve | reject | activate | deactivate. */
  bulkAction(data: { action: 'approve' | 'reject' | 'activate' | 'deactivate'; product_ids?: number[]; slugs?: string[] }) {
    return client.post<{ updated?: number; action?: string }>('/catalog/admin/products/bulk/', data)
  },
  /** API.md: result_count=0 (zero-result only), limit (default 100, max 500) */
  getSearchLog(params?: { result_count?: number; limit?: number }) {
    return client.get<{ results?: unknown[] }>('/catalog/admin/search-log/', { params })
  },
  /** Buyer reports for products missing from catalog (with photos). */
  listMissingProductReports(params?: { status?: string; limit?: number; offset?: number }) {
    return client.get<{
      results?: MissingProductReportRow[]
      count?: number
      total?: number
    }>('/catalog/admin/reports/missing-products/', { params })
  },
  updateMissingProductReport(id: number, payload: { status: MissingProductReportStatus }) {
    return client.patch<MissingProductReportRow>(`/catalog/admin/reports/missing-products/${id}/`, payload)
  },
  /** API.md + IMPORT.md: POST /catalog/admin/import/categories/ — multipart file (CSV or .xlsx). Returns { message, created, errors }. */
  importCategories(file: File, config?: AxiosRequestConfig) {
    const form = new FormData()
    form.append('file', file)
    return client.post<{ message?: string; created?: number; errors?: string[] }>(
      '/catalog/admin/import/categories/',
      form,
      config,
    )
  },
  /** API.md + IMPORT.md: POST /catalog/admin/import/brands/ — multipart file (CSV or .xlsx). */
  importBrands(file: File, config?: AxiosRequestConfig) {
    const form = new FormData()
    form.append('file', file)
    return client.post<{ message?: string; created?: number; errors?: string[] }>('/catalog/admin/import/brands/', form, config)
  },
  /** API.md + IMPORT.md: POST /catalog/admin/import/catalog/ — multipart file (CSV or .xlsx). Requires seller_id, title, base_price in file. */
  importCatalog(file: File, config?: AxiosRequestConfig) {
    const form = new FormData()
    form.append('file', file)
    return client.post<{ message?: string; created?: number; errors?: string[] }>('/catalog/admin/import/catalog/', form, config)
  },
}

/** Seller catalog. API.md: create (category_id, optional brand_id or slug), update, delete, media; view (auth). */
export const catalogSellerApi = {
  /** Seller catalog list (all statuses). GET /catalog/seller/products/ */
  listProducts(params?: {
    page?: number
    page_size?: number
    search?: string
    status?: string
    verification_status?: string
    is_active?: boolean
  }) {
    return client.get<{
      results: unknown[]
      total?: number
      count?: number
      page?: number
      page_size?: number
    }>('/catalog/seller/products/', { params })
  },
  /** Own product only (any status). GET /catalog/seller/products/:slug/ */
  getMyProductBySlug(slug: string) {
    return client.get(`/catalog/seller/products/${encodeURIComponent(slug)}/`)
  },
  /** Create product. API.md: title, description, base_price, category_id, optional brand_id, status draft|published, skus, specification. Backend may accept category/brand as slug. */
  createProduct(data: Record<string, unknown>) {
    return client.post('/catalog/products/create/', data)
  },
  /** Record product view for recommendations. Optional search_query when user came from search. */
  recordView(productId: number, searchQuery?: string) {
    const body = searchQuery != null && searchQuery.trim() ? { search_query: searchQuery.trim() } : undefined
    return client.post<{ message?: string }>(`/catalog/products/${productId}/view/`, body)
  },
  getProduct(id: number) {
    return client.get(`/catalog/products/by-id/${id}/`)
  },
  getProductBySlug(slug: string) {
    return client.get(`/catalog/products/${slug}/`)
  },
  updateProduct(slug: string, data: Record<string, unknown>) {
    return client.put(`/catalog/products/${slug}/update/`, data).catch(() => client.patch(`/catalog/products/${slug}/update/`, data))
  },
  updateProductWithCover(slug: string, formData: FormData, config?: AxiosRequestConfig) {
    return client.patch(`/catalog/products/${slug}/update/`, formData, config)
  },
  deleteProduct(slug: string) {
    return client.delete(`/catalog/products/${slug}/delete/`)
  },
  /** API.md: multipart file, optional caption, is_primary, max_width, max_height, crop_*, quality */
  addMedia(slug: string, formData: FormData, config?: AxiosRequestConfig) {
    return client.post(`/catalog/products/${slug}/media/`, formData, config)
  },
  /** PATCH media: caption, is_primary (set true to make this the cover). */
  updateMedia(slug: string, mediaId: number, data: { caption?: string; is_primary?: boolean }) {
    return client.patch(`/catalog/products/${slug}/media/${mediaId}/`, data)
  },
  deleteMedia(slug: string, mediaId: number) {
    return client.delete(`/catalog/products/${slug}/media/${mediaId}/`)
  },
  listSellerCategories() {
    return client.get<{ results: unknown[] }>('/catalog/seller/categories/')
  },
  suggestCategory(data: { name: string; slug?: string }) {
    return client.post('/catalog/seller/categories/suggest/', data)
  },
  /** Same columns as admin catalog import; `seller_id` in file is optional/ignored. POST /catalog/seller/import/catalog/ */
  importCatalog(file: File, config?: AxiosRequestConfig) {
    const form = new FormData()
    form.append('file', file)
    return client.post<{ message?: string; created?: number; errors?: string[] }>(
      '/catalog/seller/import/catalog/',
      form,
      config,
    )
  },
  /** Buyer reports targeting this seller's store. */
  listMissingProductReports(params?: { status?: string; limit?: number; offset?: number }) {
    return client.get<{
      results?: MissingProductReportRow[]
      count?: number
      total?: number
    }>('/catalog/seller/reports/missing-products/', { params })
  },
}
