import { setTitle } from './meta'
import { kkooMeta } from './kkoo-meta'

export const kkooAdminRoutes = [
    { path: '/admin/redemptions', name: 'admin.redemptions', meta: { title: setTitle('Redemptions'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Redemptions.vue') },
    { path: '/admin/redemptions/:id', name: 'admin.redemptions.detail', meta: { title: setTitle('Redemption Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/RedemptionDetail.vue') },
    { path: '/admin/reward-settings', name: 'admin.reward-settings', meta: { title: setTitle('Reward Settings'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/RewardSettings.vue') },
    { path: '/admin/catalog/brands', name: 'admin.catalog.brands', meta: { title: setTitle('Brands'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/CatalogBrands.vue') },
    { path: '/admin/catalog/categories', name: 'admin.catalog.categories', meta: { title: setTitle('Categories'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/CatalogCategories.vue') },
    { path: '/admin/catalog/products', name: 'admin.catalog.products', meta: { title: setTitle('Products'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/CatalogProducts.vue') },
    { path: '/admin/catalog/products/create', name: 'admin.catalog.products.create', meta: { title: setTitle('Create Product'), ...kkooMeta }, component: () => import('@/views/kkoo/seller/ProductCreateWizard.vue') },
    { path: '/admin/catalog/products/:slug/edit', name: 'admin.catalog.products.edit', meta: { title: setTitle('Edit Product'), ...kkooMeta }, component: () => import('@/views/kkoo/seller/ProductEdit.vue') },
    { path: '/admin/catalog/products/:slug', name: 'admin.catalog.products.detail', meta: { title: setTitle('Product Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/ProductDetail.vue') },
    { path: '/admin/catalog/media', name: 'admin.catalog.media', meta: { title: setTitle('Media'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/CatalogMedia.vue') },
    { path: '/admin/catalog/import', name: 'admin.catalog.import', meta: { title: setTitle('Import products'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/CatalogImportHub.vue') },
    { path: '/admin/orders', name: 'admin.orders', meta: { title: setTitle('Orders'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Orders.vue') },
    { path: '/admin/orders/:id', name: 'admin.orders.detail', meta: { title: setTitle('Order Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/OrderDetail.vue') },
    { path: '/admin/returns', name: 'admin.returns', meta: { title: setTitle('Returns'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Returns.vue') },
    { path: '/admin/returns/:id', name: 'admin.returns.detail', meta: { title: setTitle('Return Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/ReturnDetail.vue') },
    { path: '/admin/disputes', name: 'admin.disputes', meta: { title: setTitle('Disputes'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Disputes.vue') },
    { path: '/admin/ride-promotions', name: 'admin.ride-promotions', meta: { title: setTitle('Ride Promotions'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/RidePromotions.vue') },
    { path: '/admin/search-log', name: 'admin.search-log', meta: { title: setTitle('Search Log'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/SearchLog.vue') },
    { path: '/admin/catalog/missing-product-reports', name: 'admin.catalog.missing-product-reports', meta: { title: setTitle('Missing Product Reports'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/MissingProductReports.vue') },
    { path: '/admin/promotions', name: 'admin.promotions', meta: { title: setTitle('Promotions'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Promotions.vue') },
    { path: '/admin/promotions/:id', name: 'admin.promotions.detail', meta: { title: setTitle('Promotion Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PromotionDetail.vue') },
    { path: '/admin/promotions/bundles', name: 'admin.promotions.bundles', meta: { title: setTitle('Promotion Bundles'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PromotionBundles.vue') },
    { path: '/admin/payouts', name: 'admin.payouts', meta: { title: setTitle('Payouts'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Payouts.vue') },
    { path: '/admin/payouts/:id', name: 'admin.payouts.detail', meta: { title: setTitle('Payout Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PayoutDetail.vue') },
    { path: '/admin/payout-methods', name: 'admin.payout-methods', meta: { title: setTitle('Payment Methods'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PayoutMethods.vue') },
    { path: '/admin/regional-settings', name: 'admin.regional-settings', meta: { title: setTitle('Regional Settings'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/RegionalSettings.vue') },
    { path: '/admin/logistics', name: 'admin.logistics', meta: { title: setTitle('Logistics'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Logistics.vue') },
    { path: '/admin/logistics/zones', name: 'admin.logistics.zones', meta: { title: setTitle('Delivery Zones'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/LogisticsZones.vue') },
    { path: '/admin/logistics/settings', name: 'admin.logistics.settings', meta: { title: setTitle('Logistics Settings'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/LogisticsSettings.vue') },
    { path: '/admin/logistics/drivers/:id', name: 'admin.drivers.detail', meta: { title: setTitle('Driver Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/DriverDetail.vue') },
    { path: '/admin/kyc-documents', name: 'admin.kyc-documents', meta: { title: setTitle('KYC Documents'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/KycDocuments.vue') },
    { path: '/admin/document-types', name: 'admin.document-types', meta: { title: setTitle('Document Types'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/DocumentTypes.vue') },
    { path: '/admin/document-requirements', name: 'admin.document-requirements', meta: { title: setTitle('Document Requirements'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/DocumentRequirements.vue') },
    { path: '/admin/partner-oauth', name: 'admin.partner-oauth', meta: { title: setTitle('Partner OAuth'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PartnerOAuthClients.vue') },
    { path: '/admin/referral-stats', name: 'admin.referral-stats', meta: { title: setTitle('Referral Stats'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/ReferralStats.vue') },
    { path: '/admin/premium', name: 'admin.premium', meta: { title: setTitle('Premium Programs'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Premium.vue') },
    { path: '/admin/weekly-pass', name: 'admin.weekly-pass', meta: { title: setTitle('Weekly Pass'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/WeeklyPass.vue') },
    { path: '/admin/flash-sales', name: 'admin.flash-sales', meta: { title: setTitle('Flash Sales'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/FlashSales.vue') },
    { path: '/admin/platform-campaigns', name: 'admin.platform-campaigns', meta: { title: setTitle('Platform Campaigns'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/PlatformCampaigns.vue') },
    { path: '/admin/group-orders', name: 'admin.group-orders', meta: { title: setTitle('Group Orders'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/GroupOrdersInfo.vue') },
    { path: '/admin/users', name: 'admin.users', meta: { title: setTitle('Users'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Users.vue') },
    { path: '/admin/users/:id', name: 'admin.users.detail', meta: { title: setTitle('User Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/UserDetail.vue') },
    { path: '/admin/sellers', name: 'admin.sellers', meta: { title: setTitle('Seller Management'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Sellers.vue') },
    { path: '/admin/sellers/:id', name: 'admin.sellers.detail', meta: { title: setTitle('Seller Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/SellerDetail.vue') },
    { path: '/admin/analytics', name: 'admin.analytics', meta: { title: setTitle('Analytics'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Analytics.vue') },
    { path: '/admin/vouchers', name: 'admin.vouchers', meta: { title: setTitle('Vouchers'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Vouchers.vue') },
    { path: '/admin/verticals/shop', name: 'admin.verticals.shop', meta: { title: setTitle('Shop'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/verticals/AdminVerticalShop.vue') },
    { path: '/admin/verticals/groceries', name: 'admin.verticals.groceries', meta: { title: setTitle('Groceries'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/verticals/AdminVerticalGroceries.vue') },
    // New canonical URL: /admin/restaurants
    { path: '/admin/restaurants', name: 'admin.restaurants-menu', meta: { title: setTitle('Restaurants & Menu'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/RestaurantsMenu.vue') },
    // Backwards-compatible alias
    { path: '/admin/restaurants-menu', redirect: { name: 'admin.restaurants-menu' } },
    { path: '/admin/stock', name: 'admin.stock', meta: { title: setTitle('Stock'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Stock.vue') },
    { path: '/admin/invoices', redirect: { name: 'admin.crm.invoices' } },
    // New canonical URL: /admin/hotels
    { path: '/admin/hotels', name: 'admin.hotel', meta: { title: setTitle('Hotels'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/Hotel.vue') },
    // Backwards-compatible alias
    { path: '/admin/hotel', redirect: { name: 'admin.hotel' } },
    // CRM / Business (SME)
    { path: '/admin/crm', name: 'admin.crm.dashboard', meta: { title: setTitle('CRM Dashboard'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmDashboard.vue') },
    { path: '/admin/crm/businesses', name: 'admin.crm.businesses', meta: { title: setTitle('Businesses'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmBusinesses.vue') },
    { path: '/admin/crm/businesses/:id', name: 'admin.crm.businesses.detail', meta: { title: setTitle('Business Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmBusinessDetail.vue') },
    { path: '/admin/crm/customers', name: 'admin.crm.customers', meta: { title: setTitle('Customers'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmCustomers.vue') },
    { path: '/admin/crm/customers/:id', name: 'admin.crm.customers.detail', meta: { title: setTitle('Customer Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmCustomerDetail.vue') },
    { path: '/admin/crm/products', name: 'admin.crm.products', meta: { title: setTitle('Products (Inventory)'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmProducts.vue') },
    { path: '/admin/crm/products/create', name: 'admin.crm.products.create', meta: { title: setTitle('Create Product'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmProductCreate.vue') },
    { path: '/admin/crm/products/:id', name: 'admin.crm.products.detail', meta: { title: setTitle('Product Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmProductDetail.vue') },
    { path: '/admin/crm/invoices', name: 'admin.crm.invoices', meta: { title: setTitle('Invoices'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmInvoices.vue') },
    { path: '/admin/crm/invoices/create', name: 'admin.crm.invoices.create', meta: { title: setTitle('Create Invoice'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmInvoiceCreate.vue') },
    { path: '/admin/crm/invoices/:id', name: 'admin.crm.invoices.detail', meta: { title: setTitle('Invoice Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmInvoiceDetail.vue') },
    { path: '/admin/crm/debts', name: 'admin.crm.debts', meta: { title: setTitle('Debts'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmDebts.vue') },
    { path: '/admin/crm/debts/:id', name: 'admin.crm.debts.detail', meta: { title: setTitle('Debt Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmDebtDetail.vue') },
    { path: '/admin/crm/expenses', name: 'admin.crm.expenses', meta: { title: setTitle('Expenses'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmExpenses.vue') },
    { path: '/admin/crm/suppliers', name: 'admin.crm.suppliers', meta: { title: setTitle('Suppliers'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmSuppliers.vue') },
    { path: '/admin/crm/suppliers/:id', name: 'admin.crm.suppliers.detail', meta: { title: setTitle('Supplier Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmSupplierDetail.vue') },
    { path: '/admin/crm/purchase-orders', name: 'admin.crm.purchase-orders', meta: { title: setTitle('Purchase Orders'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmPurchaseOrders.vue') },
    { path: '/admin/crm/purchase-orders/:id', name: 'admin.crm.purchase-orders.detail', meta: { title: setTitle('Purchase Order Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmPurchaseOrderDetail.vue') },
    { path: '/admin/crm/employees', name: 'admin.crm.employees', meta: { title: setTitle('Employees'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmEmployees.vue') },
    { path: '/admin/crm/employees/:id', name: 'admin.crm.employees.detail', meta: { title: setTitle('Employee Detail'), ...kkooMeta }, component: () => import('@/views/kkoo/admin/crm/CrmEmployeeDetail.vue') },
]
